### ISSUE TITLE
Which is used, "print" or "dead code"?

### ISSUE THREAD

**Issue by skkuai** [ALFA-group/adversarial-code-generation#3]
Hello.  I'm a beginner researcher in Korea.
I think your work  is very cool.
I have a question about your paper, so I leave an issue.

If we have decided where to insert new tokens, which is used among "print" or "dead code"?

**Comment by shashank-srikant** [comment]
Thanks for your interest in our paper.

We use both `print` statements and dead code to insert new tokens. We just use `print` statements to illustrate our point in the paper.

See https://github.com/ALFA-group/adversarial-code-generation/blob/master/tasks/astor-apply-transforms/app.py#L663 for details.
